# Generated by Django 2.2 on 2020-01-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='./uploads/promotion/img')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nouveaute.Gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='./uploads/event/img')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nouveaute.Gallery')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./uploads/gallery/display/img')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('video_url', models.CharField(blank=True, max_length=100, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='nouveaute.Gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='./uploads/compagne/img')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nouveaute.Gallery')),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
            },
        ),
    ]
