# Generated by Django 2.2 on 2020-02-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintv', '0002_auto_20200206_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_True',
            field=models.BooleanField(default=True, verbose_name='Vrais?'),
        ),
    ]
