# Generated by Django 2.2 on 2020-02-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintv', '0004_auto_20200206_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='campaign',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='participation',
            name='medium',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='participation',
            name='source',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Source'),
        ),
    ]
