# Generated by Django 2.2 on 2020-02-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintv', '0007_auto_20200207_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.ImageField(blank=True, null=True, upload_to='./tickets'),
        ),
    ]
