# Generated by Django 2.2 on 2020-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintv', '0007_auto_20200207_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='ticket_base64',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ticket',
            field=models.ImageField(blank=True, null=True, upload_to='./tickets'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
