# Generated by Django 2.2 on 2020-02-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saintv', '0008_auto_20200207_1026'),
        ('saintv', '0008_auto_20200207_1405'),
    ]

    operations = [
    ]
