# Generated by Django 2.2 on 2020-01-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./uploads/images/flatepages')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Paragraphe')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ordre')),
                ('template_name', models.CharField(blank=True, choices=[('default.html', 'flatpages/default.html'), ('default_decouvrir.html', 'flatpages/default_decouvrir.html')], help_text="Example: 'flatpages/contact_page.html'. If this isn't provided, the system will use 'flatpages/default.html'.", max_length=70, verbose_name='templates name')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_flatpages.Gallery')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(upload_to='./uploads/images/flatepages/display/img')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_flatpages.Gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
