# Generated by Django 2.2 on 2020-01-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nouveaute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='./uploads/category/img')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='./uploads/group/img')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(upload_to='./uploads/marque/slide/img')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='./uploads/marque/img')),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('phone_second', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('localisation', models.ImageField(blank=True, null=True, upload_to='./uploads/marque/img')),
                ('floor', models.CharField(blank=True, default='', max_length=50)),
                ('open_hours', models.TextField(blank=True, default='')),
                ('week_open_hours', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='marque.Category')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nouveaute.Gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marque.Group'),
        ),
    ]
