# Generated by Django 2.2 on 2020-01-16 13:10

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(upload_to='./uploads/bureau/img')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bureaux',
            },
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(upload_to='./uploads/discover/img')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(upload_to='./uploads/hotel/img')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=service.models.get_info_default_order)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/icon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/logo')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img')),
                ('background_image2', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img')),
                ('parallax_mobile_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img')),
                ('parallax_mobile_image2', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img')),
                ('rdc', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/plan')),
                ('first_floor', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/plan')),
                ('second_floor', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/plan')),
                ('bureau_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('hotel_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('decouvrir_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('plan_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('horaires_acces_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('compagne_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('event_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('promotion_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('nouveautes_banner', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/banner')),
                ('shopping_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('restauration_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('cinema_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('culture_loisirs_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('hypermarche_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('promotion_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('compagne_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('facebook_image', models.ImageField(blank=True, null=True, upload_to='./uploads/preference/img/')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('copyright', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='./uploads/service/icon')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='./uploads/service/img')),
                ('principal', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=service.models.get_service_default_order)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date dernière mise à jour')),
                ('image', models.ImageField(help_text='width>=1600px height>=600px ratio:"height/width"≍0.3', upload_to='./uploads/slider/img')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('url_text', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=service.models.get_slider_default_order)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
